# This is a basic workflow to help you get started with Actions

name: CI-PGNWDB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  devsecops-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v4

      - name: configurer docker
        uses: docker/setup-buildx-action@v3

      - name: docker compose up
        run: |
          docker compose up -d

      - name: verifier conteneurs
        run: |
          docker compose ps -a

      - name: trivy installation
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'image'
          format: table
          output: "rapport.txt"
          
